# Generated by Django 5.1.3 on 2024-11-16 18:34

from django.db import migrations

from django.contrib.auth.models import Group

def create_default_groups_and_permissions(apps, schema_editor):
    # Create groups if they don't exist
    writer_group, created = Group.objects.get_or_create(name='Writer')
    basic_user_group, created = Group.objects.get_or_create(name='Basic User')

def reverse_create_default_groups_and_permissions(apps, schema_editor):
    # Reverse function to delete the groups if the migration is rolled back
    Group.objects.filter(name__in=['Writer', 'Basic User']).delete()



class Migration(migrations.Migration):

    dependencies = [ 
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_groups_and_permissions, reverse_code=reverse_create_default_groups_and_permissions),
    ]
