# Generated by Django 5.1.3 on 2024-11-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_populate_default_groups_and_permissions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
