services:
    db:
        image: postgres:15-bookworm
        container_name: postgres_db
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: poetry
        ports:
            - '5432:5432'
        volumes:
            - zinary_poetry_local:/var/lib/postgresql/data

volumes:
    zinary_poetry_local_db_data:
