# Generated by Django 5.1.3 on 2024-11-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='poet',
            table='poets',
        ),
    ]
