# Generated by Django 5.1.3 on 2024-11-16 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('first_hemistich', models.CharField(max_length=255)),
                ('second_hemistich', models.CharField(max_length=255)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.poem')),
            ],
            options={
                'db_table': 'verses',
            },
        ),
    ]
